server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuzqwe/springcloud-config-1.git
          search-paths:
            - springcloud-config-1
          skip-ssl-validation: true    #跳过ssl验证
      label: master
  rabbitmq:
    host: 192.168.130.102
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka


#暴露监控刷新
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
