server:
  port: 7002

eureka:
  instance:
    #    服务注册中心实例的主机名
    hostname: eureka7002.com
  client:
    #    是否向服务注册中心注册自己
    registerWithEureka: false
    #    是否检索服务
    fetchRegistry: false
    #    服务注册中心的配置内容，指定服务注册中心的位置
    serviceUrl:
      # 如果配置了密码
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      #没有密码的配置
      defaultZone: http://eureka7001.com:7001/eureka/